# Generated by Django 4.0.6 on 2022-07-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.SlugField(max_length=10)),
                ('httpurl', models.URLField()),
            ],
        ),
    ]
