# Generated by Django 4.0.6 on 2022-07-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_id',
            field=models.CharField(max_length=10),
        ),
    ]
