# Generated by Django 4.0.6 on 2022-07-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0003_urls_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='httpurl',
            field=models.URLField(unique=True),
        ),
    ]
