# Generated by Django 4.0.6 on 2022-07-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0004_alter_urls_httpurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='httpurl',
            field=models.URLField(),
        ),
    ]
